### ISSUE TITLE
would you mind providing the code which generates the saliency maps

### ISSUE THREAD

**Issue by Amethystjomo** [avakanski/Attention-Enriched-DL-Model-for-Breast-Tumor-Segmentation#1]

**Comment by avakanski** [comment]
Hello,
The method for obtaining saliency maps was devised by a collaborator of one of the co-authors, Dr. Fei Xu. I cannot share the code for generating the saliency maps because I was not involved in developing it, but if you contact Dr. Fei Xu (Fei.Xu@inl.gov) I believe that she will be willing to share the codes.
If you have any additional questions please let me know.
Alex
